name: Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload
      uses: actions/upload-pages-artifact@v4.0.0
      with:
        path: dist/

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4